### PR TITLE
Change "Why Larq?" menu item to "About"

### PR DESCRIPTION
**Pull request by lgeiger**
Having a FAQ under "Why Larq?" is not really intuitive. I think changing the heading to "About" makes sense or should we name it differently?

### CODE REVIEW

**Comment by lgeiger** [comment]
> The sidebar in the about page. now looks a little weird. Not sure how to fix it though.

I agree. We could change the title of the about page to something more descriptive, but I am also not sure what the best title would be. Any suggestions?

**Comment by jneeven** [comment]
I'd suggest just switching them around: the title becomes "About", and the title of what is currently "about" (https://larq.dev/about/) can change to "Why Larq?"

**Comment by lgeiger** [comment]
> I'd suggest just switching them around: the title becomes "About", and the title of what is currently "about" (https://larq.dev/about/) can change to "Why Larq?"

I changed it. @AdamHillier What do you think?

**Comment by AdamHillier** [comment]
Yep looks better

**Pull request merged**
