### PR TITLE
Add SwishSign quantizer

### PR DESCRIPTION
**Pull request by lgeiger**
I added this quantizer some time ago, but never pushed it. This adds the swish sign quantizer from https://arxiv.org/abs/1812.11800

Note that this doesn't implement a trainable beta. So we might not want to merge this right away, but wait until I find time to implement a learnable beta parameter which might change the API of this function.

### CODE REVIEW

**Comment by jamescook106** [comment]
@lgeiger tests are failing

**Comment by lgeiger** [comment]
It looks like class serialization in TF 1.13 is broken. I am skipping this test for now.

I also tried using a trainable beta, but the naive implementation doesn't correctly get the gradient. I only skimmed the paper, so I am not sure if there is a formula mentioned there. We can look into that once we train some models with this quantizer.

**Comment by lgeiger** [comment]
> Is it worth adding in the documentation that beta here is non learnable, whereas in the paper it is?

I think it is fine since all the ImageNet experiments in the paper don't use a learnable beta either

**Comment by jamescook106** [comment]
Please rebase this, and I will re-review and merge

**Comment by lgeiger** [comment]
I will push a rebased version once #182 is merged or closed, since this will introduce more conflicts.

**Comment by MariaHeuss** [comment]
I will review once the rebased version is pushed.

**Comment by lgeiger** [comment]
This is now rebased and ready for review.

**Comment by lgeiger** [comment]
I agree, that having a unit test for the backwards pass would be great. Though since the function for the backwards pass is not trivial (and I would need to implement it again in numpy any way), I tried to keep it simple and just compared the plot in the docs with the figure in the paper to check that it is correct.

Do you think that is enough? Otherwise I can add a unit test tomorrow.

> it may be nice to have an integration test for the backward pass, e.g. by running something like our optimizer test for each quantizer. But that can be done in separate PR.

Our docs build exercises the backwards pass for every quantizer, so we already have a sanity check that way.

**Comment by koenhelwegen** [comment]
Fair point. I do think it would be better to have the test, if only for consistency (for the other quantizers it's also just a numpy reimplementation), but I'm fine either way.

**Comment by lgeiger** [comment]
> Fair point. I do think it would be better to have the test, if only for consistency (for the other quantizers it's also just a numpy reimplementation), but I'm fine either way.

Sorry for being lazy. I added a unit test for the gradient in d952063

**Pull request merged**
