### PR TITLE
Fix zero division bug in summary for weightless models

### PR DESCRIPTION
**Pull request by jneeven**

### CODE REVIEW

**Comment by jneeven** [comment]
> Could you explain the bug in more detail? As I can't see it when looking at the code you have changed

If you have a model with no weights (e.g. a noop model for testing purposes), the ratio of binary weights to total weights will be a division by zero. Same for the memory size etc.

**Comment by jamescook106** [comment]
@jneeven is that because ```self.fp_equivalent_memory``` goes to 0?

**Comment by jneeven** [comment]
@jamescook106 exactly, `self.op_count` and `self.fp_equivalent_memory` will be 0

**Comment by jamescook106** [comment]
@jneeven could be worth adding another test?

**Pull request merged**
